### ISSUE TITLE
half-precision

### ISSUE THREAD

**Issue by pedropgusmao** [TimoSaemann/ENet#5]
Is it possible to convert a pre-trained ENet into a half-precision version?
Thanks

**Comment by TimoSaemann** [comment]
This question is independent of ENet but rather a general question. Did you ask this on caffe-users as well?
I think in general this should be possible. However, this does not speed up the network, because caffe-enet does not support fp16 operations. 
The Caffe framework from Nvidia supports fp16 operations: https://github.com/NVIDIA/caffe
If you like to use ENet with fp16, you have to make all necessary modifications to the NVIDIA/caffe, which were done at caffe-enet.

**Comment by pedropgusmao** [comment]
Thanks
